
```{r}
dane <- read_excel("dane/Dane_powiaty.xlsx", sheet=1) %>% mutate(X1=round(X1,1),X2=round(X2,1),X3=round(X3,1),X4=round(X4,1),X5=round(X5,1),X6=round(X6,1),X7=round(X7,1),X8=round(X8,1),X9=round(X9,1), Kod =substr(Kod,1,4)) %>% rename(JPT_KOD_JE=Kod)

zmienne<- read_xlsx("dane/Dane_powiaty.xlsx", sheet=2) 


```

```{r}
#loading shp files

woj <-st_read('Wojewodztwa/Wojewodztwa.shp')
powiaty <-st_read("powiaty/Powiaty.shp")
head(powiaty)
```

```{r}
#merging data from powiaty using JPT_KOD_JE
powiaty_all <-left_join(powiaty, dane) 

```

```{r}
tm_shape(powiaty_all) +
  tm_polygons(col ='X8')
```
```{r}
#cartogram for X8
X8 <-tm_shape(powiaty_all) +
  tm_polygons(col="X8", palette=c('springgreen4','palegreen3','palegreen2','palegreen','papayawhip','peachpuff1','sienna1','sienna3'),
  labels=c('3183-3688','3688-3795','3795-3913','3913-4019','4019-4166','4166-4313','4313-4615','4615-8488'),
  breaks=c(3183,3688,3795,3913,4019,4166,4313,4615,8488)) +
  tm_shape(woj) +
  tm_borders(col='black',lwd=2)
summary(dane$X8)
X8
tmap_save(X8,'chart.png', height=7)
```
```{r}
#chart for X8 voivodship wielkopolskie
dane_wlkp <-dane %>% filter(substr(JPT_KOD_JE ,1,2)=='30')

powiaty_wlkp <-powiaty[substr(powiaty$JPT_KOD_JE,1,2)=='30',]
powiaty_wlkp_all <- left_join(powiaty_wlkp,dane_wlkp)
```
```{r}

```

